connections:
    postgres:
        dialect: postgres
        tables:
            comment_reactions:
                fields:
                    - name: comment_id
                      include: base
                    - name: profile_id
                      include: base
                    - name: reaction_name
                      include: base
                    - name: created_at
                      include: base
                    - name: updated_at
                      include: base
                additions: []
            comments:
                fields:
                    - name: id
                      include: base
                    - name: post_id
                      include: base
                    - name: profile_id
                      include: base
                    - name: parent_comment_id
                      include: base
                    - name: content
                      include: base
                    - name: created_at
                      include: none
                    - name: updated_at
                      include: base
                additions: []
            follows:
                fields:
                    - name: follower_profile_id
                      include: base
                    - name: followed_profile_id
                      include: base
                    - name: approved_at
                      include: base
                    - name: created_at
                      include: base
                    - name: updated_at
                      include: base
                additions: []
            medias:
                fields:
                    - name: id
                      include: base
                    - name: post_id
                      include: base
                    - name: media_type
                      include: base
                    - name: ordering
                      include: base
                    - name: created_at
                      include: base
                    - name: updated_at
                      include: base
                additions: []
            post_reactions:
                fields:
                    - name: post_id
                      include: base
                    - name: profile_id
                      include: base
                    - name: reaction_name
                      include: base
                    - name: created_at
                      include: base
                    - name: updated_at
                      include: base
                additions: []
                joins:
                    - type: parented
                      table: post_reactions
                      fields:
                        - profile_id
                        - profile_id.user_id
                        - post_id
                        - post_id.profile_id
                        - post_id.profile_id.user_id
            posts:
                fields:
                    - name: id
                      include: base
                    - name: profile_id
                      include: base
                    - name: caption
                      include: base
                    - name: visit_count
                      include: base
                      feature:
                        - sort
                        - increase
                    - name: visibility
                      include: base
                    - name: created_at
                      include: base
                    - name: updated_at
                      include: base
                additions: []
            profiles:
                fields:
                    - name: id
                      include: base
                    - name: user_id
                      include: base
                    - name: handle
                      include: base
                    - name: display_name
                      include: base
                      feature:
                        - sort
                    - name: bio
                      include: base
                    - name: is_public
                      include: base
                      feature:
                        - filter
                    - name: created_at
                      include: base
                    - name: updated_at
                      include: base
                additions: []
            users:
                fields:
                    - name: id
                      include: base
                    - name: oid
                      include: base
                    - name: username
                      include: base
                    - name: email
                      include: base
                    - name: password_hash
                      include: none
                    - name: totp_secret
                      include: none
                    - name: is_active
                      include: base
                    - name: metadata
                      include: base
                    - name: created_at
                      include: base
                    - name: updated_at
                      include: base
                additions:
                    - name: picture_url
                      package: null
                      type: string
                    - name: settings
                      package: example/type/prop
                      type: UserSettings
